### ISSUE TITLE
[bug] player tp the residence then server tps got high mstp

### ISSUE THREAD

**Issue by whohhnb** [Folium-MC/Residence-Maven#7]
player use the command 
`/res tp`
the server will got and high mstp
look this
![image](https://github.com/Folium-MC/Residence-Maven/assets/108384401/e9a7c20d-9219-4f9d-85b4-317b69ec7d4d)
this is video
https://whohhnb.github.io/me/videos/1687577084719.mp4
but,use `/res tpset`  set teleportation points' residence,this problem does not arise

**Comment by lRENyaaa** [comment]
官方版本已经支持folia,这个issue不再有用
